buidodat/datn-hn5

- app/Http/Controllers/Admin/ComboController.php
- app/Http/Controllers/Admin/MovieController.php
- resources/views/admin/cinemas/create.blade.php
- resources/views/admin/cinemas/index.blade.php
- resources/views/admin/combos/create.blade.php
- resources/views/admin/combos/edit.blade.php
- resources/views/admin/combos/index.blade.php
> sửa lại giao diện crud combo, cinemas

- public/theme/client/css/my-account.css
> update giao dien client my-account

- public/theme/client/css/login.css
- resources/views/client/forgot-password.blade.php
- resources/views/client/login.blade.php
- resources/views/client/register.blade.php
> reponsive login/register/forgot-pass

- app/Http/Controllers/Admin/MovieController.php
- app/Http/Requests/Admin/UpdateMovieRequest.php
- public/theme/admin/assets/css/mainstyle.css
- resources/views/admin/layouts/master.blade.php
- resources/views/admin/movies/edit.blade.php
> update moive (not delete language)

- app/Http/Controllers/Admin/BranchController.php
- resources/views/admin/branches/create.blade.php
- resources/views/admin/branches/index.blade.php
- resources/views/admin/layouts/sidebar.blade.php
- routes/admin.php
> Thay đổi city->branch

- app/Http/Controllers/Admin/ComboController.php
- database/migrations/2024_09_05_140321_create_combo_items_table.php
- resources/views/admin/combos/create.blade.php
- resources/views/admin/layouts/master.blade.php
- resources/views/admin/layouts/sidebar.blade.php
> sửa lại giao diện add, list combo

- app/Http/Controllers/Admin/FoodController.php
- app/Http/Requests/Admin/StoreFoodRequest.php
- app/Http/Requests/Admin/UpdateFoodRequest.php
- database/migrations/2024_09_05_140321_create_combo_items_table.php
- resources/views/admin/food/create.blade.php
- resources/views/admin/food/edit.blade.php
- resources/views/admin/food/index.blade.php
> xử lý các chức năng list, add, update(food)

- app/Http/Controllers/Admin/CinemaController.php
- app/Http/Requests/Admin/StoreCinemaRequest.php
- app/Http/Requests/Admin/StoreFoodRequest.php
- app/Http/Requests/Admin/UpdateCinemaRequest.php
- app/Models/Cinema.php
- database/migrations/2024_09_01_101402_create_cinemas_table.php
- database/migrations/2024_09_01_101405_create_rooms_table.php
- public/theme/client/css/responsive2.css
- resources/views/admin/cinemas/create.blade.php
- resources/views/admin/cinemas/edit.blade.php
- resources/views/admin/cinemas/index.blade.php
> sửa lại tên bảng cinemas, tạo chứa năng list, add, update(cinema) tronng admin + validate

- resources/views/admin/layouts/master.blade.php
- resources/views/client/layouts/master.blade.php
- resources/views/client/layouts/partials/css.blade.php
- resources/views/client/login.blade.php
> responsive contact mobile

- app/Http/Controllers/Admin/SlideShowController.php
- app/Http/Controllers/Admin/VoucherController.php
- app/Http/Requests/Admin/StoreSlideShowRequest.php
- app/Http/Requests/Admin/UpdateSlideShowRequest.php
- composer.lock
- resources/views/admin/layouts/sidebar.blade.php
- resources/views/admin/slideshows/create.blade.php
- resources/views/admin/slideshows/edit.blade.php
- resources/views/admin/slideshows/index.blade.php
- routes/admin.php
> crud admin slideshow

- app/Http/Controllers/Admin/VoucherController.php
- app/Http/Requests/Admin/StoreVoucherRequest.php
- app/Http/Requests/Admin/UpdateVoucherRequest.php
- resources/views/admin/vouchers/create.blade.php
- resources/views/admin/vouchers/edit.blade.php
- resources/views/admin/vouchers/index.blade.php
> crud admin voucher

- app/Http/Controllers/Admin/BranchController.php
- app/Http/Requests/Admin/StoreBranchRequest.php
- app/Http/Requests/Admin/UpdateBranchRequest.php
- composer.json
- composer.lock
- resources/views/admin/branches/edit.blade.php
- resources/views/admin/branches/index.blade.php
- routes/api.php
> CRUD branches nhưng chưa call api về được

- app/Http/Controllers/Admin/PaymentController.php
- app/Http/Requests/Admin/StorePaymentRequest.php
- app/Http/Requests/Admin/UpdatePaymentRequest.php
- app/Http/Requests/Admin/UpdateTypeSeatRequest.php
- resources/views/admin/payments/edit.blade.php
- resources/views/admin/payments/index.blade.php
> CRUD validate đầy đủ payments và sửa lại update type_seats

- README.md
- app/Http/Controllers/Admin/ComboController.php
- app/Http/Requests/Admin/StoreComboRequest.php
- app/Models/Combo.php
- app/Models/ComboFood.php
- backup/combo/ComboController.php
- backup/combo/create.blade.php
- database/migrations/2024_09_05_140321_create_combo_food_table.php
- public/theme/admin/assets/js/combos/create.js
- resources/views/admin/combos/create.blade.php
- resources/views/admin/combos/index.blade.php
> chức năng add, list combo

- app/Http/Controllers/Admin/ContactController.php
- app/Http/Requests/Admin/StoreContactRequest.php
- app/Models/Contact.php
- resources/views/admin/contacts/create.blade.php
- resources/views/admin/contacts/index.blade.php
> CRD contact admin

- app/Http/Controllers/Admin/UserController.php
- app/Http/Controllers/Client/MovieDetailController.php
- database/seeders/DatabaseSeeder.php
- resources/views/admin/users/index.blade.php
- resources/views/admin/users/show.blade.php
- resources/views/client/home.blade.php
- resources/views/client/layouts/header.blade.php
- resources/views/client/movie-detail.blade.php
- routes/web.php
> Movie detail & show user

- app/Http/Controllers/Client/ContactController.php
- app/Http/Requests/Client/StoreContactRequest.php
- resources/views/client/contact.blade.php
- routes/web.php
> create contact client

- public/theme/client/css/login.css
- resources/views/auth/passwords/email.blade.php
- resources/views/auth/passwords/reset.blade.php
> fix laji giao dien trang wuen mat khau va reset mat khau

- public/theme/client/css/login.css
- resources/views/admin/slideshows/index.blade.php
- resources/views/client/layouts/slideshow.blade.php
> sửa lại quên mật khẩu login và  slideshow

- public/theme/client/css/my-account.css
- public/theme/client/js/my-account.js
- resources/views/client/my-account.blade.php
> Update interface my account

- app/Http/Controllers/Auth/LoginFacebookController.php
- app/Models/User.php
- composer.json
- composer.lock
- config/services.php
- resources/views/auth/login.blade.php
- routes/web.php
> Luc ph37171

- app/Http/Controllers/Admin/MyAccountController.php
- app/Http/Requests/Admin/UpdateMyAcountRequest.php
- index.html
- resources/views/admin/my-accounts/edit.blade.php
- resources/views/admin/my-accounts/show.blade.php
- routes/admin.php
> Giao diện My Account + thay đổi thông tin tài khoản, thay đổi mật khẩu bằng ajax siêu xịn và chuyên nghiệp 

- app/Http/Controllers/Client/UserController.php
- composer.lock
- resources/views/client/my-account.blade.php
- routes/web.php
> Đổi mật khẩu gửi email client

- app/Http/Controllers/Admin/ContactController.php
- app/Models/Contact.php
- database/migrations/2024_08_28_155552_create_contacts_table.php
- resources/views/admin/contacts/edit.blade.php
- resources/views/admin/contacts/index.blade.php
Thêm trường dữ liệu status
Cập nhật
> Thêm status ở contact admin và làm sửa 

- app/Http/Controllers/Client/CheckoutController.php
- app/Http/Controllers/Client/MovieDetailController.php
- app/Models/User.php
- public/theme/client/js/mainjs.js
- resources/views/client/movie-detail.blade.php
- routes/web.php
> Fix lại chức năng hủy voucher và sửa lại trang hiển thị bình luận

- README.md
- app/Http/Controllers/Auth/GoogleAuthController.php
- config/services.php
- database/migrations/2014_10_12_000000_create_users_table.php
- resources/views/auth/login.blade.php
- routes/web.php
> đăng nhập bằng google

- app/Http/Controllers/Auth/GoogleAuthController.php
- database/migrations/2014_10_12_000000_create_users_table.php
> Fix lại đăng nhập bằng google nhé

- resources/views/admin/branches/index.blade.php
- resources/views/admin/cinemas/index.blade.php
- resources/views/admin/combos/index.blade.php
- resources/views/admin/contacts/index.blade.php
- resources/views/admin/food/index.blade.php
- resources/views/admin/movies/index.blade.php
- resources/views/admin/payments/index.blade.php
- resources/views/admin/rooms/index.blade.php
- resources/views/admin/showtimes/index.blade.php
- resources/views/admin/slideshows/index.blade.php
- resources/views/admin/type_seats/index.blade.php
- resources/views/admin/users/create.blade.php
- resources/views/admin/users/index.blade.php
- resources/views/admin/vouchers/index.blade.php
> Format lại ngày tháng năm theo định dạng dd/mm/Y, nút thêm mới, chỉnh lại nút thêm sửa xóa ở tất cả các trang

- app/Http/Controllers/API/MovieController.php
- app/Http/Controllers/API/RoomController.php
- app/Http/Controllers/Admin/MovieController.php
- app/Http/Controllers/Admin/RoomController.php
- app/Http/Requests/Admin/StoreMovieRequest.php
- app/Http/Requests/Admin/UpdateMovieRequest.php
- app/Models/Movie.php
- app/Models/Room.php
- config/constant.php
- database/migrations/2024_08_30_155009_create_movies_table.php
- database/migrations/2024_09_01_101405_create_rooms_table.php
- database/seeders/DatabaseSeeder.php
- resources/views/admin/movies/create.blade.php
- resources/views/admin/movies/edit.blade.php
- resources/views/admin/movies/index.blade.php
- resources/views/admin/rooms/index.blade.php
- resources/views/admin/rooms/seat-diagram.blade.php
- routes/api.php
> fix create + edit movie có giá vé theo phim & index thay đổi is_active is_hot ở index

- app/Http/Controllers/Admin/ShowtimeController.php
- public/theme/admin/apps-ecommerce-order-details.html
- resources/views/admin/showtimes/index.blade.php
- resources/views/admin/showtimes/show.blade.php
> ADMIN: hiển thị chi tiết suất chiếu

- README.md
- app/Http/Controllers/Client/PaymentController.php
- resources/views/client/checkout.blade.php
- routes/web.php
Sử dụng thẻ visa để thanh toán
Thanh toán thành công
> Tích hợp thanh toán online ZaloPay

- app/Models/Movie.php
- app/Models/Ticket.php
- app/Models/TicketSeat.php
- database/migrations/2024_09_01_104736_create_ticket_seats_table.php
- database/seeders/DatabaseSeeder.php
**mỗi tài khoản sẽ có 1 vé 1 ghế ngẫu nhiên. và 1 vé có 3 ghế ngồi cạnh nhau**
> Sửa lại fake data tické_seat và ticket

- app/Http/Controllers/Client/HomeController.php
- resources/views/client/home.blade.php
> Đổ dữ liệu tin tức ra trang chủ

- app/Http/Controllers/Admin/TicketPriceController.php
- app/Http/Requests/Admin/UpdateTicketPriceRequest.php
- resources/views/admin/book-tickets/checkout.blade.php
- resources/views/admin/ticket-price.blade.php
- resources/views/admin/vouchers/create.blade.php
- routes/admin.php
> Update + Validate 3 bảng thành công !

- app/Http/Controllers/Client/TicketPriceController.php
- resources/views/client/layouts/header.blade.php
- resources/views/client/ticket-price.blade.php
- routes/web.php
> Giá vé theo chi nhánh

- app/Http/Controllers/Admin/PostController.php
- app/Http/Controllers/Client/PostController.php
- app/Models/Post.php
- app/Models/User.php
- database/migrations/2024_08_28_155348_create_posts_table.php
- database/seeders/DatabaseSeeder.php
- resources/views/client/posts/index.blade.php
- resources/views/client/posts/show.blade.php
> Thêm id người đăng bài viết

- app/Http/Controllers/Admin/PostController.php
- app/Http/Controllers/Client/UserController.php
- public/theme/client/css/my-account.css
- resources/views/client/posts/index.blade.php
- resources/views/client/users/my-account.blade.php
- routes/web.php
> Không tải reaload đổi mật khẩu client

- app/Http/Controllers/API/UpdateActiveController.php
- app/Http/Controllers/Admin/BranchController.php
- app/Http/Controllers/Admin/CinemaController.php
- app/Http/Controllers/Admin/ComboController.php
- app/Http/Controllers/Admin/FoodController.php
- app/Models/Food.php
- resources/views/admin/branches/index.blade.php
- resources/views/admin/cinemas/index.blade.php
- resources/views/admin/combos/index.blade.php
- resources/views/admin/food/index.blade.php
- resources/views/admin/posts/index.blade.php
- resources/views/admin/showtimes/index.blade.php
- resources/views/admin/slideshows/index.blade.php
- resources/views/admin/vouchers/index.blade.php
- routes/api.php
…ow,post,showtime & Thêm chức năng xóa cho branches, cinemas , food
> update is_active  Thêm chức năng xóa cho branches, cinemas , food

- app/Console/Commands/ExpirePoints.php
- app/Console/Commands/ResetMembership.php
- app/Console/Kernel.php
- app/Http/Controllers/Admin/RankController.php
- app/Http/Controllers/Client/UserController.php
- app/Http/Requests/Admin/StoreRankRequest.php
- app/Http/Requests/Admin/UpdateRankRequest.php
- app/Models/PointHistory.php
- app/Models/Rank.php
- database/migrations/2024_10_24_073636_create_ranks_table.php
- database/migrations/2024_10_24_073659_create_point_histories_table.php
- database/seeders/DatabaseSeeder.php
- resources/views/admin/ranks/index.blade.php
- routes/admin.php
> Full CRUD Rank  chạy bằng cách url/admin/ranks

- app/Http/Controllers/Client/PaymentController.php
- database/migrations/2024_09_01_104750_create_ticket_combos_table.php
- database/seeders/DatabaseSeeder.php
- public/theme/client/css/mainstyle.css
- public/theme/client/css/showtimes-cinema.css
- resources/views/client/checkout.blade.php
- resources/views/client/choose-seat.blade.php
- resources/views/client/showtimes.blade.php
> css lại trang(showtime, choose-seat, checkout"admin+member"), xóa status bảng ticket_combos

- app/Http/Controllers/Admin/SlideShowController.php
- app/Http/Requests/Admin/StoreSlideShowRequest.php
- resources/views/admin/combos/create.blade.php
- resources/views/admin/slideshows/create.blade copy.php
- resources/views/admin/slideshows/create.blade.php
- resources/views/admin/slideshows/index.blade.php
> sửa lại trang add slide
